<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-05T12:18:17Z" name="Default suite" finished-at="2024-10-05T12:18:19Z" duration-ms="2181">
    <groups>
    </groups>
    <test started-at="2024-10-05T12:18:17Z" name="Default test" finished-at="2024-10-05T12:18:19Z" duration-ms="2181">
      <class name="Project3.EndToEndTest">
        <test-method signature="TC01_GetAllEmployee()[pri:0, instance:Project3.EndToEndTest@7c8c9a05]" started-at="2024-10-05T12:18:17Z" name="TC01_GetAllEmployee" finished-at="2024-10-05T12:18:18Z" duration-ms="1284" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_GetAllEmployee -->
        <test-method signature="TC02_GetSingleEmployee()[pri:0, instance:Project3.EndToEndTest@7c8c9a05]" started-at="2024-10-05T12:18:18Z" name="TC02_GetSingleEmployee" finished-at="2024-10-05T12:18:18Z" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_GetSingleEmployee -->
        <test-method signature="TC03_CreateEmployee()[pri:0, instance:Project3.EndToEndTest@7c8c9a05]" started-at="2024-10-05T12:18:18Z" name="TC03_CreateEmployee" finished-at="2024-10-05T12:18:19Z" duration-ms="807" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03_CreateEmployee -->
        <test-method signature="TC04_DeleteEmployee()[pri:0, instance:Project3.EndToEndTest@7c8c9a05]" started-at="2024-10-05T12:18:19Z" name="TC04_DeleteEmployee" finished-at="2024-10-05T12:18:19Z" duration-ms="19" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC04_DeleteEmployee -->
        <test-method signature="TC05_TestDeletedEmployee()[pri:0, instance:Project3.EndToEndTest@7c8c9a05]" started-at="2024-10-05T12:18:19Z" name="TC05_TestDeletedEmployee" finished-at="2024-10-05T12:18:19Z" duration-ms="18" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at Project3.EndToEndTest.TC05_TestDeletedEmployee(EndToEndTest.java:88)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC05_TestDeletedEmployee -->
      </class> <!-- Project3.EndToEndTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
